openapi: 3.1.0
info:
  title: Money Book API Server
  version: '1.0'
  summary: Money Book API Server.
  contact:
    name: Calvin C. Chan
    email: hello@calvin-c.com
servers:
  - url: 'http://localhost:50420'
    description: Local
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  '/months/{id}':
    get:
      summary: Get Month
      tags: []
      responses: {}
      operationId: get-month
      description: Get a month summary document.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Month ID in YYYY-MM format
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Month:
      type: object
      x-examples:
        example-1:
          _id: 100
          year: 2022
          month: 4
          openingBalance: 0
          closingBalance: -422400
          value: -422400
          dateFrom: '2022-03-31T16:00:00.000Z'
          dateTo: '2022-04-30T15:59:59.999Z'
          days:
            - day: 1
              value: -300000
            - day: 2
              value: 0
            - day: 3
              value: 0
            - day: 4
              value: 0
            - day: 5
              value: 0
            - day: 6
              value: 0
            - day: 7
              value: 0
            - day: 8
              value: 0
            - day: 9
              value: 0
            - day: 10
              value: 0
            - day: 11
              value: 0
            - day: 12
              value: 0
            - day: 13
              value: 0
            - day: 14
              value: -100
            - day: 15
              value: 0
            - day: 16
              value: 0
            - day: 17
              value: 0
            - day: 18
              value: 0
            - day: 19
              value: 0
            - day: 20
              value: 0
            - day: 21
              value: 0
            - day: 22
              value: 0
            - day: 23
              value: 0
            - day: 24
              value: 0
            - day: 25
              value: 0
            - day: 26
              value: -12300
            - day: 27
              value: -110000
            - day: 28
              value: 0
            - day: 29
              value: 0
            - day: 30
              value: 0
          createdAt: '2022-04-26T13:34:37.163Z'
          updatedAt: '2022-04-26T23:35:22.955Z'
          __v: 0
      properties:
        year:
          type: number
          description: Year ID
        month:
          type: number
          description: Month ID
        openingBalance:
          type: number
          description: Opening balance of the month
        closingBalance:
          type: number
          description: Closing balance of the month
        value:
          type: number
          description: Total value of all transactions in the month
        dateFrom:
          type: string
          minLength: 1
          description: Start date of the month
        dateTo:
          type: string
          minLength: 1
          description: End date of the month
        days:
          type: array
          uniqueItems: true
          minItems: 1
          description: Day summary
          items:
            type: object
            properties:
              day:
                type: number
                description: Day of month (base-1)
              value:
                type: number
                description: Total value of all transactions of the day
        createdAt:
          type: string
          minLength: 1
        updatedAt:
          type: string
          minLength: 1
